name: eyesight_flutter
description: Demo DR screening app with TFLite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6  
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  collection: ^1.18.0
  shared_preferences: ^2.2.3
  google_mlkit_face_detection: ^0.13.1
  permission_handler: ^11.3.1
  pdf: ^3.11.0
  printing: ^5.13.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/charts/
   


